# Introduction to Python

##  1 Basic Syntax and Variable Assignment
Let's walk through Basic Syntax and Variable Assignment in Python, along with example code and commentary to help learners transition from R.

### 1.1 Variable Assignment

In Python, assignment uses the = symbol instead of <- as in R. Python variables don’t require an explicit declaration, and their type is inferred from the assigned value. Variable names should be lowercase with underscores for readability, and Python is case-sensitive.

In [4]:
# Assigning values to variables
x = 10         # integer assignment
y = 3.14       # float assignment
name = "Alice" # string assignment
is_active = False  # boolean assignment

# Printing variable values to check assignments
print(x)       # Output: 10
print(y)       # Output: 3.14
print(name)    # Output: Alice
print(is_active)  # Output: True

10
3.14
Alice
False

In Python, you can check a variable's type using the `type()` function:

In [5]:
# Checking types
print(type(x))        # Output: <class 'int'>
print(type(y))        # Output: <class 'float'>
print(type(name))     # Output: <class 'str'>
print(type(is_active)) # Output: <class 'bool'>

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>

### 1.2 Basic Data Types

Python's basic data types map well to those in R:

* Integers (int): Whole numbers like 10 or -3
* Floating-point numbers (float): Decimal numbers like 3.14 or -0.001
* Strings (str): Text data enclosed in quotes (single or double)
* Booleans (bool): Logical values True and False

In [6]:
# Integer and float arithmetic
a = 5
b = 2.0
print(a + b)  # Output: 7.0 (int and float result in float)

# Strings
message = "Hello, Python!"
print(message) # Output: Hello, Python!

7.0
Hello, Python!

### 1.3 Comments and Code Style

Python uses # for comments, similar to R, and Python follows an indentation-based syntax for block structures (like functions or loops). This is different from R’s {} braces and ensures code readability.

In [ ]:
# This is a single-line comment

"""
Multi-line comments can be written
using triple quotes. This is useful
for longer descriptions.
"""

### 1.4 Basic Operations

... Add your personal **comments** any time here ...

> Some blockquote display

Arithmetic operations in Python are similar to R:

* `+` (addition), `-` (subtraction), `*` (multiplication), `/` (division)
* `**` (exponentiation, like `^` in R)
* `//` (integer division)
* `%` (modulus for remainders)

In [7]:
# Basic arithmetic
a = 7
b = 3
my_new_variable = "lalalalal"

print(a + b)  # Output: 10
print(a - b)  # Output: 4
print(a * b)  # Output: 21
print(a / b)  # Output: 2.3333333333333335 (division always returns float)
print(a // b) # Output: 2 (integer division)
print(a % b)  # Output: 1 (remainder of 7 divided by 3)
print(a ** b) # Output: 343 (7 raised to the power of 3)
print(my_new_variable)

10
4
21
2.3333333333333335
2
1
343
lalalalal

### 1.5 String Operations

Strings in Python can be concatenated using + and repeated using *. This is different from R, where string concatenation is often handled by functions like paste().

In [8]:
# Concatenating strings
first_name = "Alice"
last_name = "Smith"
full_name = first_name + " " + last_name  # Adding a space between names
print(full_name)  # Output: Alice Smith

# Repeating strings
echo = "Echo! " * 3
print(echo)  # Output: Echo! Echo! Echo!

Alice Smith
Echo! Echo! Echo!

## 2 Basic Data Structures

Let’s explore Basic Data Structures in Python. In Python, commonly used data structures include lists, tuples, and dictionaries, which serve different purposes and have key differences from R's vectors, lists, and data frames.

### 2.1 Lists

Python lists are versatile, ordered, and mutable (modifiable). They are similar to R’s vectors, but Python lists can hold elements of multiple data types, unlike R vectors, which are typically of a single type.

In [9]:
# Creating a list
numbers = [1, 2, 3, 4, 5]           # list of integers
mixed_list = [1, "two", 3.0, True]  # list with multiple data types

print(numbers)       # Output: [1, 2, 3, 4, 5]
print(mixed_list)    # Output: [1, 'two', 3.0, True]

# Accessing elements (indexing starts at 0, unlike R where it starts at 1)
print(numbers[0])    # Output: 1
print(numbers[-1])   # Output: 5 (negative indexing accesses from the end)

# Modifying elements
numbers[1] = 200
print(numbers)       # Output: [1, 200, 3, 4, 5]

[1, 2, 3, 4, 5]
[1, 'two', 3.0, True]
1
5
[1, 200, 3, 4, 5]

Common List Operations:

Lists in Python support appending, removing, and slicing elements, as well as some basic list-specific methods like `append`, `remove`, and `extend`.

In [10]:
# Adding elements
numbers.append(6)       # Adds 6 to the end
print(numbers)          # Output: [1, 200, 3, 4, 5, 6]

# Removing elements
numbers.remove(200)     # Removes the first occurrence of 200
print(numbers)          # Output: [1, 3, 4, 5, 6]

# Slicing elements (extracting a sub-list)
subset = numbers[1:4]   # Extracts elements from index 1 up to (but not including) index 4
print(subset)           # Output: [3, 4, 5]

[1, 200, 3, 4, 5, 6]
[1, 3, 4, 5, 6]
[3, 4, 5]

### 2.2 Tuples

Tuples are similar to lists but are immutable (cannot be changed after creation). They are often used for fixed collections of items. Tuples can be useful when returning multiple values from functions or when you want to ensure that data remains unchange

In [14]:
# Creating a tuple
coordinates = (10, 20)
print(coordinates)      # Output: (10, 20)
print(type(coordinates))

# Accessing elements (similar to lists)
print(coordinates[1])   # Output: 10

# Trying to modify a tuple will raise an error
# coordinates[0] = 30   # Uncommenting this line would raise a TypeError

(10, 20)
<class 'tuple'>
20

### 2.3 Dictionaries

Dictionaries are Python’s equivalent to named lists or associative arrays in other languages, including R's list or named list. They store data in key-value pairs and are highly flexible for structured data.

In [19]:
# Creating a dictionary
person = {
    "name": "Alice",
    "age": 30,
    "is_student": False
}

print(person)           # Output: {'name': 'Alice', 'age': 30, 'is_student': False}

# Accessing values by keys
print(person["name"])   # Output: Alice
print(person.get("age")) # Output: 30
print(person["age"])
print(list(person.keys()))

# Adding and updating key-value pairs
person["occupation"] = "Engineer"    # Adding a new key-value pair
person["age"] = 31                   # Updating an existing key
print(person)           # Output: {'name': 'Alice', 'age': 31, 'is_student': False, 'occupation': 'Engineer'}

# Removing key-value pairs
del person["is_student"]
print(person)           # Output: {'name': 'Alice', 'age': 31, 'occupation': 'Engineer'}

{'name': 'Alice', 'age': 30, 'is_student': False}
Alice
30
30
['name', 'age', 'is_student']
{'name': 'Alice', 'age': 31, 'is_student': False, 'occupation': 'Engineer'}
{'name': 'Alice', 'age': 31, 'occupation': 'Engineer'}

Common Dictionary Operations:

Python dictionaries support various operations for managing key-value data.

In [21]:
# Checking if a key exists
print("name" in person)   # Output: True
print("salary" in person) # Output: False

# Iterating over keys and values
for key, value in person.items():
    print(key + "lalala", ":", value)
# Output:
# name : Alice
# age : 31
# occupation : Engineer

True
False
namelalala : Alice
agelalala : 31
occupationlalala : Engineer

### 2.4 Comparison Summary (R vs. Python)

* Lists in Python are flexible and can store multiple data types, like R’s lists, but are ordered collections similar to R’s vectors.
* Tuples are like immutable lists, used when data should remain constant.
* Dictionaries in Python offer named key-value pairs, similar to R’s named lists, but with fast access and clear keys, which is ideal for structured data.

## 3 Control Structures

For Control Structures in Python, we’ll cover conditional statements, loops, and list comprehensions. These provide the backbone for decision-making and repetition in Python.

### 3.1 Conditional Statements

In Python, conditional statements use `if`, `elif`, and `else` to control code execution based on conditions, similar to if and else if in R. Python relies on indentation instead of braces to define blocks, so correct indentation is crucial.

In [25]:
# Basic if-elif-else structure
x = -10

if x > 0:
    print("x is positive")           # This will run if x > 0
    print("here is the value of x: " + str(x))
elif x == 0:
    print("x is zero")               # This runs if the first condition is False and x == 0
else:
    print("x is negative")           # This runs if all previous conditions are False
# Output: x is positive

x is negative

Comparison and Logical Operators:

Python uses operators like == (equal), != (not equal), >, <, >=, <= for comparisons, and logical operators and, or, and not.

In [28]:
# Using logical operators
age = 25
has_ticket = True

if age >= 18 and has_ticket:
    print("Allowed to enter")  # Both conditions must be True
else:
    print("Not allowed")
# Output: Allowed to enter

Allowed to enter

### 3.2 Loops

Python has for and while loops, each with specific use cases:

* For loops iterate over sequences (like lists, tuples, or ranges).
* While loops execute as long as a condition remains True.

**For Loop**

A for loop in Python can directly iterate over items in a sequence, similar to R’s for loop but with simpler syntax.

In [31]:
list(range(5))

[0, 1, 2, 3, 4]

In [29]:
# For loop over a list
fruits = ["apple", "banana", "cherry"]

for fruit in fruits:
    print(fruit)
# Output:
# apple
# banana
# cherry

# Using range() in a for loop
for i in range(5):
    print(i)
# Output: 0 1 2 3 4
# range(5) generates numbers from 0 to 4 (5 is not included)

# Caution: Lists in Python start with 0-index, while vectors in R start with index 1.

apple
banana
cherry
0
1
2
3
4

**While Loop**

The while loop runs until a specified condition becomes False. This loop is useful when the number of iterations isn’t known beforehand.

In [32]:
# While loop example
count = 0

while count < 5:
    print(count)
    count += 1  # Increment count by 1 each time
# Output: 0 1 2 3 4

0
1
2
3
4

### 3.3 List Comprehensions

Python list comprehensions provide a compact way to create lists. They’re like `lapply` or `sapply` functions in R, used for generating lists based on some conditions or transformations, with syntax similar to a loop in one line.

In [33]:
# Creating a list of squares using a list comprehension
squares = [x**2 for x in range(1, 6)]
print(squares)  # Output: [1, 4, 9, 16, 25]

# Filtering with a list comprehension (only even numbers)
even_squares = [x**2 for x in range(1, 6) if x % 2 == 0]
print(even_squares)  # Output: [4, 16]

[1, 4, 9, 16, 25]
[4, 16]

### Additional Control Flow Tips

Break and Continue: Use break to exit a loop early and continue to skip the rest of the current iteration.

In [34]:
# Example with break and continue
for i in range(5):
    if i == 3:
        break        # Exit loop when i is 3
    elif i == 1:
        continue     # Skip when i is 1, in R this is next
    print(i)
# Output: 0 2

0
2

Summary: R vs. Python Comparison

* If-else structure: Python uses indentation rather than braces.
* List comprehensions: Python’s list comprehensions provide a powerful way to generate lists, which might be done with lapply in R.

## 4 Functions

Moving on to Functions in Python, which work similarly to functions in R but with some differences in syntax, scoping, and flexibility. We'll cover defining functions, using arguments (including default and keyword arguments), and Python's lambda expressions for concise, single-line functions.


### 4.1 Defining Functions

In Python, functions are defined using the def keyword, followed by the function name, parentheses for parameters, and a colon. The function body is indented. Python functions use return to output a result, just like in R.

In [35]:
# Basic function definition
def greet(name):
    # here is the function body
    return f"Hello, {name}!"

# Calling the function
print(greet("Alice"))  # Output: Hello, Alice!

Hello, Alice!

Unlike in R, Python uses f-strings (formatted strings) for easy variable interpolation in strings, as shown above.

### 4.2 Arguments and Parameters

Functions in Python can take multiple parameters, and arguments can be provided as positional or keyword arguments. This provides flexibility in function calls, as arguments can be matched by order or by name.

In [37]:
# Function with multiple arguments
def add(a, b):
    summed_value = a + b
    return summed_value

# Calling with positional arguments
print(add(3, 4))       # Output: 7

# Calling with keyword arguments
print(add(b=5, a=10))  # Output: 15

7
15

### 4.3 Default Arguments

Python allows you to set default values for function parameters, which is similar to specifying default values in R functions. This is useful for optional parameters.

In [38]:
# Function with a default argument
def greet(name, greeting="Hello"):
    return f"{greeting}, {name}!"

print(greet("Alice"))                 # Output: Hello, Alice!
print(greet("Alice", greeting="Hi"))  # Output: Hi, Alice!

Hello, Alice!
Hi, Alice!

Here, if no greeting argument is provided, it defaults to "Hello".

### 4.4 Variable Scope

Python functions have local scope for variables defined within them, meaning variables created inside a function aren’t accessible outside it. This is similar to R but is worth noting, especially when functions call other functions or reference global variables.

In [41]:
# Example showing local scope
def example_function():
    local_var = "I'm local"
    return local_var

print(example_function())  # Output: I'm local
# print(local_var)         # Uncommenting this will raise a NameError since local_var is not defined outside the function

I'm local

## 5 Modules and Packages

We now focus on Python's way of organizing and reusing code. In Python, code can be structured into modules and packages. A module is a single .py file containing functions, classes, and variables, while a package is a collection of modules organized within a directory. This setup enables easier maintenance, reusability, and organization of larger codebases.
5.1 Using Modules

Modules in Python are essentially single Python files (ending in `.py`) that contain code. Built-in modules (like `math`, `random`, or `datetime`) come pre-installed with Python, and additional modules can be created by users or installed via libraries.
Importing Modules

To use a module’s functionality, we `import` it using the import keyword. Imported functions, classes, and variables from a module are then accessible via dot notation (e.g., module_name.function_name).

In [42]:
# Importing the math module for mathematical functions
import math

# Using a function from the math module
print(math.sqrt(16))       # Output: 4.0 (square root of 16) # in R it is math::sqrt
print(math.pi)             # Output: 3.141592653589793

4.0
3.141592653589793

Alternatively, we can import specific functions directly, which eliminates the need for dot notation:

In [ ]:
# Importing specific functions directly
from math import sqrt, pi

print(sqrt(25))            # Output: 5.0
print(pi)                  # Output: 3.141592653589793

**Aliasing Modules**

Modules can be given shorter or custom names (aliases) using the as keyword. This is particularly helpful when working with long module names, such as import pandas as pd.

In [ ]:
# Importing with an alias
import math as m

print(m.sqrt(9))           # Output: 3.0

**Installing Third-Party Libraries**

Python uses pip (Python’s package manager) to install third-party libraries, such as numpy for numerical computations, pandas for data manipulation, and matplotlib for plotting. This is similar to R’s install.packages().

In [44]:
# Installing a package from the command line (not run in Python code)
!pip install pandas

# In Colab Notebooks, we can run console commands with a ! prepended to it

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

Once installed, libraries can be imported and used like any standard library.

In [46]:
# Using the pandas library to create a DataFrame
import pandas as pd

data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)
print(df)
# Output:
#     Name  Age
# 0  Alice   25
# 1    Bob   30
df

    Name  Age
0  Alice   25
1    Bob   30

    Name  Age
0  Alice   25
1    Bob   30

## 6 File handling

In Python, File Handling is straightforward for reading from and writing to files, using built-in functions like open(). Here’s a quick overview:

### 6.1 Opening Files

The open() function opens files in different modes:

* 'r': Read (default)
* 'w': Write (overwrites if file exists)
* 'a': Append (adds to end if file exists)
* 'r+': Read and write

To write data to a file, use 'w' or 'a' mode. Remember that 'w' will overwrite the file if it exists, whereas 'a' will append to it.

In [52]:
# Writing to a file
with open('example.txt', 'w') as file:  # The 'with' statement auto-closes the file
    file.write("Hello, world!" + "\n")
    file.write("This is line 2!")

Caution: Where is the newly written file located?

In [49]:
# We locate the current working directory
import os
current_working_directory = os.getcwd()
print(current_working_directory)

/content

Now we can open the file in read mode.

In [53]:
# Opening a file for reading
file = open('example.txt', 'r')
content = file.read()   # Reads the entire file
print(content)
file.close()            # Close file after reading

Hello, world!
This is line 2!

### 6.2 Reading Line by Line

The .readline() method reads one line at a time, and .readlines() returns all lines as a list.

In [55]:
# Reading lines in a file
with open('example.txt', 'r') as file:
    lines = file.readlines()
    for i, line in enumerate(lines):
        print(str(i) + " : " + line.strip())   # Use strip() to remove newline characters

0 : Hello, world!This is line 2!

### 6.3 Using with for Automatic File Closing

The with statement is preferred as it automatically closes the file, even if an error occurs.

In [56]:
# Appending to a file with 'with'
with open('example.txt', 'a') as file:
    file.write("\nAdding another line.")

## 7 Pandas data frames

Now we cover the most basic and essential Pandas commands for data manipulation, similar to core R data.frame operations. Pandas provides a DataFrame structure that’s extremely useful for handling tabular data.

### 7.1 Importing Pandas and creating a data **frame**

Start by importing the pandas library (usually abbreviated as pd).

In [57]:
import pandas as pd

# Creating a DataFrame from a dictionary
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [24, 27, 22],
        'City': ['Berlin', 'Munich', 'Hamburg']}
df = pd.DataFrame(data)
print(df)

      Name  Age     City
0    Alice   24   Berlin
1      Bob   27   Munich
2  Charlie   22  Hamburg

### 7.2 Reading and Writing Data

Load data from a CSV file and save a DataFrame to a CSV file. These functions are similar to R’s read.csv() and write.csv().

In [58]:
# Writing to a CSV file
df.to_csv('output.csv', index=False)  # Set index=False to exclude row numbers

# Reading a CSV file
df = pd.read_csv('output.csv')

Print nicely

In [59]:
df

      Name  Age     City
0    Alice   24   Berlin
1      Bob   27   Munich
2  Charlie   22  Hamburg

### 7.3 Basic Data Inspection

Pandas provides easy-to-use functions to inspect data:

* df.head(n): Displays the first n rows (default is 5).
* df.tail(n): Displays the last n rows.
* df.shape: Shows the (rows, columns) of the DataFrame.
* df.info(): Provides a summary of the DataFrame, including data types and non-null counts.
* df.describe(): Summarizes numerical columns (mean, std, min, etc.).

In [61]:
print(df.head(2))        # First 5 rows
print(df.shape)         # (Number of rows, Number of columns)
print(df.info())        # Summary of data types and null values
print(df.describe())    # Summary statistics for numerical columns

    Name  Age    City
0  Alice   24  Berlin
1    Bob   27  Munich
(3, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes
None
             Age
count   3.000000
mean   24.333333
std     2.516611
min    22.000000
25%    23.000000
50%    24.000000
75%    25.500000
max    27.000000

### 7.4 Selecting and Filtering Data

Use loc[] for label-based selection and iloc[] for index-based selection, similar to R’s [].

In [62]:
# Selecting a single column
print(df['Age'])

# Selecting multiple columns
print(df[['Name', 'City']])

# Filtering rows based on conditions
print(df[df['Age'] > 25])

# Selecting rows by index and columns by label
print(df.loc[0:1, ['Name', 'City']])  # Rows 0 to 1 and columns 'Name' and 'City'

# Selecting rows by index position
print(df.iloc[0:2, 1:3])  # Rows 0 to 1, columns 1 to 2

0    24
1    27
2    22
Name: Age, dtype: int64
      Name     City
0    Alice   Berlin
1      Bob   Munich
2  Charlie  Hamburg
  Name  Age    City
1  Bob   27  Munich
    Name    City
0  Alice  Berlin
1    Bob  Munich
   Age    City
0   24  Berlin
1   27  Munich

### 7.5 Adding and Modifying Columns

You can easily add new columns or modify existing ones.

In [63]:
# Adding a new column based on calculations
df['Age in 5 Years'] = df['Age'] + 5

# Modifying an existing column
df['Age'] = df['Age'] - 1

In [64]:
df

      Name  Age     City  Age in 5 Years
0    Alice   23   Berlin              29
1      Bob   26   Munich              32
2  Charlie   21  Hamburg              27